La struttura base che utilizziamo per memorizzare e manipolare i dati sono array multidimensionali che chiamiamo tensors.

In [2]:
import torch

PyTorch fornisce molte funzioni utili per creare dei tensor con dei dati già all'interno. Ad esempio con `arange(n)` creiamo un tensor con numeri che partono da 0 incluso fino ad n escluso con un intervallo che possiamo specificare, di default è 1. Se non viene specificato il tensor viene creato in RAM e potrà essere utilizzato soltanto dalla CPU.

In [3]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

Ogni valore viene chiamato _element_ del tensor. Il tensor x contiene 12 elementi. Possiamo vedere quanti elementi ha un tensor con

In [4]:
x.numel()

12

I tensor sono multidimensionali e avere quindi più assi, per scoprire la lunghezza su ogni asse e vedere quindi la shape di un tensor chiamiamo appunto `shape`

In [5]:
x.shape

torch.Size([12])

Possiamo cambiare la shape di un tensor senza alterarne i valori o la grandezza chiamano `reshape`, ad esempio possiamo trasformare il tensor di lunghezza 12 in una matrice 3x4.
Il nuovo tensor manterrà tutti gli elementi ma li riorganizzerà in una matrice.

In [6]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

Specificare tutte le grandezze nel metodo `reshape` è ridondante, infatti siccome già sappiamo la grandezza del tensor possiamo ricavare alcune dimensioni a partire da altre. Ad esempio dato un tensor di grandezza $n$ che vogliamo trasformare in $(h,w)$ sappiamo che $w = n/h$. Per fare questo ci basta inserire $-1$ nel campo che vogliamo far calcolare in automatico, quindi nel codice precedente avremmo potuto scrivere `x.reshape(3,-1)` oppure `x.reshape(-1, 4)`.

PyTorch mette a disposizione delle funzioni per creare tensor con tutti 1 o 0 e specificare anche le dimensioni di ogni asse

In [7]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

Possiamo anche creare tensor con valori casuali, utile ad esempio per inizializzare i parametri di una rete neurale.
Con il seguente blocco creiamo un tensor con elementi scelti a caso da una distribuzione Gaussiana

In [9]:
torch.randn(3,4)

tensor([[ 1.9327,  0.0844,  1.0717,  0.3277],
        [-0.9750, -0.5720,  0.6752, -0.2486],
        [-0.5888,  0.2108,  1.7574,  0.0117]])

Ovviamente possiamo anche fornire noi i dati per ogni elemento attraverso liste Python

In [10]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

## Indexing and Slicing
Possiamo accedere agli elementi dei tensors in modo simile alle liste Python, possiamo utilizzare anche lo slicing per accedere a range di valori, quindi usare `X[start:stop]` per ottenere tutti i valori da `start` incluso a `stop` escluso.
Se in un array multidimensionali utilizziamo un solo indice allora questo farà riferimento all'asse 0.

In [12]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

Possiamo le posizioni anche per scrivere dati

In [13]:
X[1, 2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

O anche lo slicing, in questo caso sovrascriviamo tutte le righe fino alla 2 esclusa, e di queste tutte le colonne.

In [14]:
X[:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## Operations
Adesso possiamo iniziare a fare operazioni con i tensors, tra le più utili ci sono quelle element-wise ovvero che applicano operazioni scalari su ogni elemento del tensor. Per operazioni che prendono in input due tensor, questo tipo di operazioni lavora su coppie di elementi.

Usando una notazione matematica indichiamo queste operazioni unarie (1 input) con $f:\mathbb{R} \to \mathbb{R}$.

Molte operazioni standard possono essere applicate element-wise, ad esempio $e^x$

In [15]:
torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

Possiamo invece indicare le funzioni binarie con $f:\mathbb{R},\mathbb{R}\to\mathbb{R}$. Presi due vettori $u$ e $v$ della stessa shape e una funzione binaria $f$ possiamo creare un nuovo vettore $c=F(u,V)$ impostando $c_i = f(u_i, v_i)$ per ogni $i$, dove $c_i,u_i,v_i$ sono l'$i$-esimo elemento dei vettori $c,u,v$.

In [16]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

È anche possibile effettuare operazioni di algebra lineare come prodotto tra matrici ma le vedremo più avanti.

Si possono concatenare più tensors fra loro, basta fornire in input quest'ultimi e anche su che asse effettuare la concatenazione

In [18]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

Nel primo caso stiamo concatenando le righe e infatti otteniamo 6 come lunghezza dell'asse 0 ovvero la somma dello stesso asse per i due tensors. Nel secondo output invece abbiamo concatenato sulle colonne e infatti l'asse 1 ha come valore 8 ovvero la somma dello stesso asse per i due tensors.

È possibile costruire tensors anche a partire da operatori logici, ad esempio con X == Y, in questo caso avremo un tensor che per ogni posizione $i,j$ se $X[i,j] == Y[i,j]$ allora avrà come valore 1 altrimenti 0.

In [19]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

Ci sono anche operazioni che convertono tensor in altri tensor composti da singoli elemnti

In [20]:
X.sum()

tensor(66.)

## Broadcasting
Le operazioni viste fino ad adesso possiamo eseguirle soltanto su tensors con la stessa dimensione. In alcuni casi però anche con shape differenti possiamo comunque eseguire operazioni elementwise, dobbiamo utilizzare il meccanismo di broadcassting.
Il broadcasting si applica in due step:
- Espandere uno o entrambi gli array sull'asse che ha lunghezza 1 copiando gli elementi
- Effettuare l'operazione su questi nuovi array

In [22]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In questo caso abbiamo $a$ e $b$ con, rispettivamente, shape 3x1 e 1x2, con il broadcasting otteniamo una matrice 3x2. La prima matrice a viene replicata sulle colonne, quindi diventerà una matrice 3x2 copiano la prima colonna sulla seconda. La matrice b diventerà anch'essa 3x2 ma copieremo la prima riga sulle altre.
Una volta effettuate queste operazione viene effettuata la somma elementwise su queste due nuove matrici, infatti otteniamo

In [23]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## Saving Memory
Eseguire operazioni comporta l'utilizzo di altra memoria nell'host, ad esempio se scriviamo Y = X + Y stiamo deferenziando il puntatore al tensor Y per fargli puntare una nuova zona di memoria, possiamo verificarlo in Python

In [24]:
before = id(Y)
Y = Y + X
id(Y) == before

False

Questo comportamento potrebbe essere scomodo per due motivi principali
- Non vogliamo allocare memoria inutilmente, in machine learning spesso avremo megabytes di parametri da aggiornare molte volte al secondo, se possibile vogliamo effettuare queste operazioni _in place_.
- In alcuni casi abbiamo diverse variabili che puntano allo stesso parametro, se non lo aggiorniamo in place dobbiamo prestare attenzione ad aggiornare tutte le reference a quel paraemtro.

Effettuare operazioni in place è semplice. Per farlo ci basta assegnare l'operazione ad un array precedente utilizzando la notazione dello slicing `Y[:]=expression`

In [25]:
Z = torch.zeros_like(Y)
print(f"id(Z): {id(Z)}")
Z[:] = X + Y
print(f"id(Z): {id(Z)}")

id(Z): 140372309656784
id(Z): 140372309656784


In realtà in questo caso se X non viene riutilizzato più avanti possiamo allocare tutto al suo interno nello stesso modo

In [26]:
before = id(X)
X += Y # Oppure X[:] = X + Y
id(X) == before

True

## Conversion to Other Python Objects
Possiamo convertire i tensor in ndarray di NumPy o vice versa, questi condivideranno la stessa memoria e quindi modificare uno comporterà anche la modifica dell'altro.

In [29]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

Infine possiamo convertire un tensor ad un solo elemento in uno scalare Python chiamando la funzione `item`

In [30]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)