# Linear Algebra
Oltre alle basiche operazioni matematica avremo bisogno di una base di algebra lineare.

In [2]:
import torch

## Scalars
Indichiamo dei semplici numeri con il termine **scalari**. Ad esempio se in un luogo abbiamo una temperatura di 72 gradi Fahrenheit e vogliamo convertirla in gradi Celsius dobbiamo calcolare l'espressione $c=\frac{5}{9}(f-32)$ impostando $f=72$. In questa equazione i valori $5,9,32$ sono scalari costanti mentre le variabili $c,f$ sono sempre scalari ma per ora sconosciuti.

Indichiamo gli scalari con lettere lower-case ($x,y,z$) e lo spazio dei valori reali di tutti gli scalari con $\mathbb{R}$. Con l'espressione $x \in \mathbb{R}$ stiamo dicendo che $x$ è uno scalare con valore reale.

Gli scalari sono implementati come tensors che contengono un solo elemento

In [3]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x+y, x*y, x/y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

## Vectors
Possiamo immaginare un vettore come un array di scalari con lunghezza fissa. Chiameremo questi scalari _elementi_ del vettore.
Quando trattiamo dati reali, i valori dei vettori avranno un significato reale, ad esempio se stiamo allenando un modello per studiare il rischio di attacchi di cuore ogni vettore rappresenterà un paziente e ogni elemento corrisponderà ad un parametro come il livello di colesterolo, i minuti di esercizio al giorno ecc...
Indichiamo i vettori con lettere lower-case in grassetto (**x,y,z**) e i loro elementi con un indice scalare in basso a destra ($\pmb{x}_2$)

I vettori sono implementati come tensors ad una dimensione.

In [4]:
x = torch.arange(3)
x

tensor([0, 1, 2])

Per indicare che un vettore contiene $n$ elementi scriviamo $\pmb{x}\in\mathbb{R}^n$, chiamiamo $n$ la dimensione del vettore. Nel codice questa corrisponde alla length che è accessibile tramite le funzioni built-in di Python

In [5]:
len(x)

3

Possiamo accedere alla lunghezza anche con l'attributo shape dei tensor, la shape è una tupla che indica la lunghezza del tensor su ogni asse, in questo caso uno solo.

In [6]:
x.shape

torch.Size([3])

Per non fare confusione con i termini, spesso utilizzati per indicare entrambe le cose:
- Order: Numero di assi
- Dimensionality: Numero di elementi su un asse

## Matrices
Le matrici sono tensor del secondo ordine e le indichiamo con lettere upper-case e in grassetto ($\pmb{X,Y,Z}$). Con l'espressione $\pmb{A}\in\mathbb{R}^{m \times n}$ indichiamo che la matrice $\pmb{A}$ contiene $m \times n$ scalari reali organizzati in $m$ righe e $n$ colonne.
Quando $m=n$ diciamo che la matrice è quadrata.
Per indicare un elemento lo facciamo con una lettere lowercase, di solito quella della matrice e i due indici in basso a sinistra, quindi $a_{ij}$ è l'elemento di $\pmb{A}$ alla riga $i$ e alla colonna $j$.

In [8]:
A = torch.arange(6).reshape(3,2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

Possiamo invertire gli assi delle matrici ovvero scambiare le righe con le colonne, il risultato di questa operazione è la trasposta di una matrice.
Indichiamo la trasposta di $\pmb{A}$ con $\pmb{A}^T$ e se $\pmb{B}=\pmb{A}^T$ allora $b_{ij}=a_{ji}$.
Notiamo quindi che la trasposta di una matrice $m\times n$ è una matrice $n\times m$

In PyTorch effettuiamo questa operazione con:

In [9]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

Una matrice si dice **simmetrica** quando è uguale alla sua trasposta. La seguente matrice è simmetrica

In [10]:
A = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

Le matrici sono estremamente utili per rappresentare i datasets, di solito le righe indicano dei singoli records mentre le colonne i loro attributi.

## Tensors
I tensors sono utili per rappresentare array di qualsiasi ordine in modo semplice. Li indichiamo con lettere upper-case e per indicare un elemento utilizziamo la stessa notazione delle matrici.

I tensors diventeranno più utili con le immagini dove useremo 3 dimensioni per ogni immagine e se appunto abbiamo una raccolta di immagini avremo anche tensor a 4 dimensioni;
- 0: Immagine
- 1: Altezza
- 2: Larghezza
- 3: Canale

In [11]:
torch.arange(24).reshape(2,3,4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])