# Linear Algebra
Oltre alle basiche operazioni matematica avremo bisogno di una base di algebra lineare.

In [11]:
import torch

## Scalars
Indichiamo dei semplici numeri con il termine **scalari**. Ad esempio se in un luogo abbiamo una temperatura di 72 gradi Fahrenheit e vogliamo convertirla in gradi Celsius dobbiamo calcolare l'espressione $c=\frac{5}{9}(f-32)$ impostando $f=72$. In questa equazione i valori $5,9,32$ sono scalari costanti mentre le variabili $c,f$ sono sempre scalari ma per ora sconosciuti.

Indichiamo gli scalari con lettere lower-case ($x,y,z$) e lo spazio dei valori reali di tutti gli scalari con $\mathbb{R}$. Con l'espressione $x \in \mathbb{R}$ stiamo dicendo che $x$ è uno scalare con valore reale.

Gli scalari sono implementati come tensors che contengono un solo elemento

In [12]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x+y, x*y, x/y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

## Vectors
Possiamo immaginare un vettore come un array di scalari con lunghezza fissa. Chiameremo questi scalari _elementi_ del vettore.
Quando trattiamo dati reali, i valori dei vettori avranno un significato reale, ad esempio se stiamo allenando un modello per studiare il rischio di attacchi di cuore ogni vettore rappresenterà un paziente e ogni elemento corrisponderà ad un parametro come il livello di colesterolo, i minuti di esercizio al giorno ecc...
Indichiamo i vettori con lettere lower-case in grassetto (**x,y,z**) e i loro elementi con un indice scalare in basso a destra ($\pmb{x}_2$)

I vettori sono implementati come tensors ad una dimensione.

In [13]:
x = torch.arange(3)
x

tensor([0, 1, 2])

Per indicare che un vettore contiene $n$ elementi scriviamo $\pmb{x}\in\mathbb{R}^n$, chiamiamo $n$ la dimensione del vettore. Nel codice questa corrisponde alla length che è accessibile tramite le funzioni built-in di Python

In [14]:
len(x)

3

Possiamo accedere alla lunghezza anche con l'attributo shape dei tensor, la shape è una tupla che indica la lunghezza del tensor su ogni asse, in questo caso uno solo.

In [15]:
x.shape

torch.Size([3])

Per non fare confusione con i termini, spesso utilizzati per indicare entrambe le cose:
- Order: Numero di assi
- Dimensionality: Numero di elementi su un asse

## Matrices
Le matrici sono tensor del secondo ordine e le indichiamo con lettere upper-case e in grassetto ($\pmb{X,Y,Z}$). Con l'espressione $\pmb{A}\in\mathbb{R}^{m \times n}$ indichiamo che la matrice $\pmb{A}$ contiene $m \times n$ scalari reali organizzati in $m$ righe e $n$ colonne.
Quando $m=n$ diciamo che la matrice è quadrata.
Per indicare un elemento lo facciamo con una lettere lowercase, di solito quella della matrice e i due indici in basso a sinistra, quindi $a_{ij}$ è l'elemento di $\pmb{A}$ alla riga $i$ e alla colonna $j$.

In [16]:
A = torch.arange(6).reshape(3,2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

Possiamo invertire gli assi delle matrici ovvero scambiare le righe con le colonne, il risultato di questa operazione è la trasposta di una matrice.
Indichiamo la trasposta di $\pmb{A}$ con $\pmb{A}^T$ e se $\pmb{B}=\pmb{A}^T$ allora $b_{ij}=a_{ji}$.
Notiamo quindi che la trasposta di una matrice $m\times n$ è una matrice $n\times m$

In PyTorch effettuiamo questa operazione con:

In [17]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

Una matrice si dice **simmetrica** quando è uguale alla sua trasposta. La seguente matrice è simmetrica

In [18]:
A = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

Le matrici sono estremamente utili per rappresentare i datasets, di solito le righe indicano dei singoli records mentre le colonne i loro attributi.

## Tensors
I tensors sono utili per rappresentare array di qualsiasi ordine in modo semplice. Li indichiamo con lettere upper-case e per indicare un elemento utilizziamo la stessa notazione delle matrici.

I tensors diventeranno più utili con le immagini dove useremo 3 dimensioni per ogni immagine e se appunto abbiamo una raccolta di immagini avremo anche tensor a 4 dimensioni;
- 0: Immagine
- 1: Altezza
- 2: Larghezza
- 3: Canale

In [19]:
torch.arange(24).reshape(2,3,4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## Basic Properties of Tensor Arithmetic
Una delle principali proprietà è che i risultati di operazioni elementwise mantengono la shape degli operandi.

In [20]:
A = torch.arange(6, dtype=torch.float32).reshape(2,3)
B = A.clone() # Alloca nuova memoria
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

Il prodotto elementwise di due matrici si chiama _Hadamart product_ e lo indichiamo con $\odot$

In [21]:
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

Sommare o moltiplcare uno scalare ed un tensor produce un risultato con la stessa shape del tensor originale

In [22]:
a = 2
X = torch.arange(24).reshape(2,3,4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

## Reduction
Possiamo calcolare la somma di tutti gli elementi di un tensor con la funzione sum.

In [23]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

Questo tipo di operazione si muove in tutte le assi, vediamo ad esempio come si comporta con una matrice

In [24]:
A.shape, A.sum()

(torch.Size([2, 3]), tensor(15.))

Quindi di default chiamare l'operazione sum agisce su tutti gli assi, possiamo però specificare su quali effettuare l'operazione, fare questo comporta la rimozione dell'asse specificato dal risultato

In [25]:
A.shape, A.sum(axis=0).shape

(torch.Size([2, 3]), torch.Size([3]))

Ovviamente lo stesso accade per le colonne

In [26]:
A.shape, A.sum(axis=1).shape

(torch.Size([2, 3]), torch.Size([2]))

Possiamo anche calcolare la media con la funzione mean

In [37]:
A.mean(), A.sum() / A.numel()

(tensor(2.5000), tensor(2.5000))

Ovviamente valgono le stesse regole di prima sulla specifica degli assi.

## Non-Reduction Sum
In alcuni casi potrebbe essere utile mantenere invariato il numero di assi quando invochiamo la funzione per calcolare la somma o la media, ad esempio quando sappiamo che utilizzeremo il meccanismo di broadcast.

In [27]:
print(A)
sum_A = A.sum(axis=1, keepdim=True)
sum_A, sum_A.shape

tensor([[0., 1., 2.],
        [3., 4., 5.]])


(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

Quindi, quando noi specifichiamo un asse stiamo dicendo a PyTorch di muoversi lungo quell'asse e sommare gli elementi per poi "distruggere" quell'asse. Se specifichiamo keepdim l'asse non verrà distrutto ma verrà ridotto a grandezza 1.

Dato che in questo modo manteniamo la shape possiamo quindi effettuare operazioni successive con il tensor dato che poi verrà applicato il broadcasting, adesso dividere ogni elemento di una riga per la somma della riga e ottenere righe che quindi hanno come somma 1.

In [28]:
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

Se vogliamo calcolare la somma cumulativa degli elementi su un certo asse senza ridurre la shape possiamo usare la funzione `cumsum`

In [29]:
A.cumsum(axis=0)

tensor([[0., 1., 2.],
        [3., 5., 7.]])

## Dot Products
Una delle principali operazioni in algebra lineare è il dot product, dati due vettori $\pmb{x,y}\in\mathbb{R}^d$ il loro dot product $\pmb{x}^T\pmb{y}=\sum_{i=1}^d x_iy_i$. Anche conosciuto come _inner product_ $<\pmb{x,y}>$

In [30]:
y = torch.ones(3, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

Questo può essere ottenuto anche effettuando prima una moltiplicazione elementwise e poi una somma.

In [31]:
torch.sum(x * y)

tensor(3.)

Il dot products è utile in molte occasioni, ad esempio dato un set di valori in un vettore $\pmb{x}\in\mathbb{R}^n$ e un set di pesi nel vettore $\pmb{w}\in\mathbb{R}^n$, la somma ponderata dei valori può essere espressa come il dot product $\pmb{x}^T\pmb{w}$. Quando i pesi sono non negativi e la loro somma è 1 allora il dot product rappresenta una media ponderata.

## Matrix-Vector Products
Possiamo vedere come calcolare il prodotto tra una matrice $m\times n \ \pmb{A}$ e un vettore a $n$ dimensioni $\pmb{x}$.

Per semplificare le cose immaginiamo la matrice $\pmb{A}$ come un vettore con $m$ righe composta da vettori lunghi $n$, chiamiamo questi vettori $a_1^T,a_2^T,...,a_m^T$. Adesso prendiamo ogni riga ed effettuiamo il prodotto con il vettore $\pmb{x}$, il risultato sarà un elemento del nuovo vettore.

Nel codice utilizziamo la funzione `mv` per effettuare questo prodotto, ovviamente per poter funzionare la dimensione delle colonne di $\pmb{A}$ deve essere la stessa lunghezza di $\pmb{x}$. Python ci offre anche un altro operatore che permette di effettuare sia prodotti matrici-vettori che matrici-matrici ovvero `@`.

In [32]:
print(A)
print(x)
A.shape, x.shape, torch.mv(A,x), A@x

tensor([[0., 1., 2.],
        [3., 4., 5.]])
tensor([0., 1., 2.])


(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

## Matrix-Matrix Multiplication
Immaginiamo di avere due matrici $\pmb{A}\in\mathbb{R}^{n\times k}$ e $\pmb{B}\in\mathbb{R}^{k\times m}$.

Adesso indichiamo con $\pmb{a}_i^T\in\mathbb{R}^k$ il vettore (riga) che rappresenta la $i$-esima riga della matrice $\pmb{A}$, mentre con $\pmb{b}_j\in\mathbb{R}^k$ il vettore (colonna) che rappresenta la colonna $j$-esima della matrice $\pmb{B}$.

Per formare la matrice risultato $\pmb{C}\in\mathbb{R}^{n\times m}$ dobbiamo calcolare ogni elemento $c_{i j}$ come il dot product tra la $i$-esima riga di $\pmb{A}$ e la $j$-esima colonna di $\pmb{B}$

In [33]:
B = torch.ones(3, 4)
print(A)
torch.mm(A, B), A@B

tensor([[0., 1., 2.],
        [3., 4., 5.]])


(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

## Norms
Un'altra categoria di operazioni utilissime in algebra sono le _norms_. In generale la norm di un vettore ci dice "quanto è grande" ovvero qual è la sua distanza dall'origine, ad esempio la $l_2$ norm misura la lugnezza Euclidea di un vettore.

Una norm function $||\cdot||$ è una funzione che mappa un vettore in uno scalare e soddisfa le 3 proprietà seguenti:
- Dato un vettore $\pmb{x}$ e uno scalare, se li moltiplichiamo allora la sua lunghezza si moltiplica per quel numero. $$||\alpha \pmb{x}|| = |\alpha|||\pmb{x}||$$
- Presi due qualsiasi vettori $\pmb{x,y}$ è soddisfatta la **Disuguaglianza Triangolare*, ovvero una linea retta tra i due punti è sempre il percorso minore $$||\pmb{x}+\pmb{y}||\leq ||\pmb{x}||+||\pmb{y}||$$
- Le lunghezze non possono essere negative, l'unico modo per avere lunghezza zero è che il vettore non si è mai mosso dall'origine. $$||\pmb{x} > 0|| \ \ \forall \pmb{x}\neq 0$$

La $l_2$ norm equivale al calcolo del teorema di Pitagora infatti è data da: $$||\pmb{x}||_2=\sqrt{\sum_{i=1}^n x_i^2}$$

In [34]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

Che infatti equivale a $\sqrt{3^2 + (-4)^2}=\sqrt{9 + 16}=5$

La $l_1$ norm invece è associata alla Manhattan distance, per definizione questa somma tutti i valori assoluti degli elementi e quindi abbiamo che: $$||\pmb{x}||_1=\sum_{i=1}^n |x_i|$$

In [35]:
torch.abs(u).sum()

tensor(7.)

Entrambe $l_1, l_2$ sono un caso speciale della norm generale $l_p$: $$||\pmb{x}||_p = \left(\sum_{i=1}^n |x_i|^p\right)^\frac{1}{p}$$

Estendere questo concetto alle matrici diventa però più complicato, come misuriamo "quanto sono grandi"? Introduciamo la **Norma di Frobenius**, possiamo vederla come il teorema di Pitagora applicato ad una matrice. $$|| \pmb{X} ||_F=\sqrt{\sum_{i=1}^m \sum_{j=1}^n x^2_{i j}}$$

In [36]:
torch.norm(torch.ones(4, 9))

tensor(6.)

Queste norm ci servono per misurare appunto la distanza tra i vettori dei risultati che ci aspettiamo e quelli predetti dal nostro modello. Addestrare una rete significa appunto cercare di rendere questa norma il più vicino possibile allo 0.